### ISSUE TITLE
ポリゴンがカーバーする指定したコード桁数の地域メッシュリストを返事する関数の追加の検討。

### ISSUE THREAD

**Issue by zrg1993** [qazsato/japanmesh#18]
このような関数を追加するのは可能でしょうか。
getCodesFromPolygon(polygon, codeLength)

**Comment by qazsato** [comment]
@zrg1993 
`japanmesh.getCodesWithinBounds` という境界内の地域メッシュコードを取得できる関数を追加しました。
https://github.com/qazsato/japanmesh?tab=readme-ov-file#japanmeshgetcodeswithinboundsbounds-level

ご利用ください。
